name: Build mpv on MacOS
env:
  #branch: 'mod-0.35.1'
  branch: 'master'

on: 
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    #runs-on: macos-10.15
    runs-on: macos-11

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ env.branch }}

      - name: Install dependencies
        run: |
            brew install dylibbundler
            brew install yasm nasm pkg-config libass ffmpeg
            brew install libarchive luajit-openresty mujs uchardet
            #brew install luajit --HEAD
            install_name_tool -change "@loader_path/libbrotlicommon.1.dylib" "/usr/local/opt/brotli/lib/libbrotlicommon.1.dylib" /usr/local/opt/brotli/lib/libbrotlidec.1.dylib
            install_name_tool -change "@loader_path/libbrotlicommon.1.dylib" "/usr/local/opt/brotli/lib/libbrotlicommon.1.dylib" /usr/local/opt/brotli/lib/libbrotlienc.1.dylib
            PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/opt/libarchive/lib/pkgconfig:/usr/local/opt/luajit-openresty/lib/pkgconfig
            echo "PKG_CONFIG_PATH=$PKG_CONFIG_PATH" >> $GITHUB_ENV

      - name: Build
        run: |
            ./bootstrap.py
            ./waf configure
            ./waf
            #TOOLS/osxbundle.py build/mpv

      - name: Build package
        if: ${{ false }}
        run: |
            mkdir -p release
            cp -r build/mpv.app release
            cd release
            tar -cjf ../mpv-macos-11.tar.bz2 *
            
      - name: Build package
        run: |
            mkdir -p package/mpv.app/Contents/MacOS/
            cp build/mpv package/mpv.app/Contents/MacOS/
            dylibbundler -od -b -x ./package/mpv.app/Contents/MacOS/mpv -d ./package/mpv.app/Contents/MacOS/lib -p @executable_path/lib
            cd package
            tar -cjf ../mpv-macos-11.tar.bz2 mpv.app/

      - name: Build Apple Disk Image
        if: ${{ false }}
        run: |
            brew install create-dmg
            create-dmg --sandbox-safe --no-internet-enable --volname "mpv" --app-drop-link 200 185 mpv-11.dmg release

      - name: Create artifact 1
        #if: ${{ false }}
        uses: actions/upload-artifact@v2
        with:
          name: mpv-macos-11.tar.bz2
          path: ./mpv-macos-11.tar.bz2

      - name: Create artifact 2
        if: ${{ false }}
        uses: actions/upload-artifact@v2
        with:
         name: mpv-11.dmg
         path: ./mpv-11.dmg

      - name: Upload package to release
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./mpv-macos-11.tar.bz2
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
